
SET SQL DIALECT 3; 

/* CREATE DATABASE 'localhost:/var/lib/firebird/dbwtldb.fdb' PAGE_SIZE 16384 DEFAULT CHARACTER SET UTF8 */


/*  Generators or sequences */
CREATE GENERATOR GEN_ALLTYPES_ID;
CREATE GENERATOR GEN_BIGDATA_ID;


/* Table: ALLTYPES, Owner: SYSDBA */
CREATE TABLE ALLTYPES (ID BIGINT NOT NULL,
        T_SMALLINT SMALLINT,
        T_INTEGER INTEGER,
        T_BIGINT BIGINT,
        T_FLOAT FLOAT,
        T_DOUBLE DOUBLE PRECISION,
        T_NUMERIC NUMERIC(10, 3),
        T_DECIMAL DECIMAL(18, 17),
        T_DATE DATE,
        T_TIME TIME,
        T_TIMESTAMP TIMESTAMP,
        T_CHAR CHAR(5),
        T_VARCHAR VARCHAR(20),
        T_BLOB BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        T_TEXT BLOB SUB_TYPE TEXT SEGMENT SIZE 16384 CHARACTER SET ISO8859_1,
CONSTRAINT PK_ALLTYPES PRIMARY KEY (ID));

/* Table: BIGDATA, Owner: SYSDBA */
CREATE TABLE BIGDATA (ID INTEGER NOT NULL,
        DATA BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        MEM BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        DATA2 BLOB SUB_TYPE 0 SEGMENT SIZE 80);

/* Table: OCTET_TEST, Owner: SYSDBA */
CREATE TABLE OCTET_TEST (NAME VARCHAR(20),
        DATA VARCHAR(10) CHARACTER SET OCTETS);

/* Table: TABLE_ONE, Owner: SYSDBA */
CREATE TABLE TABLE_ONE (ID BIGINT,
        NAME CHAR(20));

SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER ALLTYPES_BI FOR ALLTYPES 
ACTIVE BEFORE INSERT POSITION 0 
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_alltypes_id,1);
end ^

CREATE TRIGGER T1_BI FOR BIGDATA 
ACTIVE BEFORE INSERT POSITION 0 
as begin if(new.id is null) then new.id = gen_id(gen_bigdata_id, 1); end ^

COMMIT WORK ^
SET TERM ; ^
